name: Niobium FHE SDK CI

on:
  push:

permissions:
  contents: write

jobs:
  build:
    name: Building for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up SSH for Private Repo Access
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Configure Git Authentication
        env:
          GOPRIVATE: "github.com/NiobiumInc"
        run: |
          git config --global url."ssh://git@github.com/".insteadOf "https://github.com/"
      - name: Install dependencies
        run: make dep
      - name: Get OS Name & Arch
        run: |
          OS_NAME="$(echo ${{ runner.os }} | tr '[:upper:]' '[:lower:]')"
          echo "os_name=${OS_NAME}" >> $GITHUB_ENV
          if [ ${{ runner.os }} = "X64" ]; then
            ARCH_NAME=amd64
          else
            ARCH_NAME="$(echo ${{ runner.os }} | tr '[:upper:]' '[:lower:]')"
          fi
          echo "arch_name=${ARCH_NAME}" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: not_yet
        if: startsWith(github.ref, 'refs/tags/v')
