name: Niobium FHE Server Runtime System Docker

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write
  packages: write
  attestations: write
  id-token: write

env:
  REGISTRY: ghcr.io
  IMAGE_BASE: niobiuminc/niobium-server-runtime

jobs:
  build:
    name: Building for Linux
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version & revision
        run: |
          version="$(git describe --tags 2> /dev/null || echo "latest" | sed s/^v//)"
          echo "VERSION=${version}" >> "$GITHUB_ENV"
          revision="$(git rev-parse --short HEAD)"
          echo "REVISION=${revision}" >> "$GITHUB_ENV"

      - name: Get Docker image name
        run: |
          docker_image="${{ env.REGISTRY }}/${{ env.IMAGE_BASE }}:${{ env.VERSION }}"
          echo "DOCKER_IMAGE=${docker_image}" >> "$GITHUB_ENV"

      - name: Authenticate with ghcr.io
        run: |
          echo ${{ secrets.GH_PAT }} | \
            docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Set up Docker buildx
        run: |
          docker buildx create --name multiarch-builder --use --driver docker-container
          docker buildx inspect multiarch-builder --bootstrap

      - name: Build and push Docker images
        run: |
          docker buildx build \
            --file Dockerfile \
            --platform linux/amd64,linux/arm64 \
            --label org.opencontainers.image.title="Niobium FHE Server Runtime System" \
            --label org.opencontainers.image.description="Runtime environment for Niobium FHE Server and Tools." \
            --label org.opencontainers.image.version=${{ env.VERSION }} \
            --tag ${{ env.DOCKER_IMAGE }} \
            --push \
            .

      # - name: Generate image digest
      #   run: |
      #     digest="$(docker buildx imagetools inspect \
      #       ${{ env.DOCKER_IMAGE }} --raw | grep -o "sha256:[a-f0-9]*")"
      #     echo "IMAGE_DIGEST=${digest}" >> "$GITHUB_ENV"

      # - name: Generate artifact attestation
      #   uses: actions/attest-build-provenance@v1
      #   with:
      #     subject-name: ${{ env.DOCKER_IMAGE }}
      #     subject-digest: ${{ env.IMAGE_DIGEST }}
      #     push-to-registry: true
